### ISSUE TITLE
import error when file named email.py exists

### ISSUE THREAD

**Issue by shanemgrey** [petl-developers/petl#435]
When I had a file named email.py in the directory I was in while calling any of the other .py files, I got the following error:

```

(api) ❯ ./email.py
Traceback (most recent call last):
  File "./email.py", line 2, in <module>
    import petl as etl
  File "/Users/myusername/.virtualenvs/api/lib/python3.6/site-packages/petl/__init__.py", line 7, in <module>
    from petl import comparison
  File "/Users/myusername/.virtualenvs/api/lib/python3.6/site-packages/petl/comparison.py", line 7, in <module>
    from petl.compat import text_type, binary_type, numeric_types
  File "/Users/myusername/.virtualenvs/api/lib/python3.6/site-packages/petl/compat.py", line 69, in <module>
    from urllib.request import urlopen
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 86, in <module>
    import email
  File "/Users/myusername/Documents/Code/hub/etl/email.py", line 10, in <module>
    tableSource = etl.fromcsv('../data/prod_csv/participant_profile.csv', delimiter=';')
AttributeError: module 'petl' has no attribute 'fromcsv'

```

The work around was to simply give the file a different name.  But the error probably points to something not quite right in the source files.  

And hopefully if someone else is searching this error, this issue will help them find the resolution faster.

**Comment by juarezr** [comment]
@shanemgrey ,

The problem looks like your `email.py` file is conflicting with the Python Standard Library [email module](https://docs.python.org/3.6/library/email.html).

It looks like that could happen with any python script when any dependencies will import the module `urllib`.
