### ISSUE TITLE
petl.io.todb does not support qualified table name on postgres

### ISSUE THREAD

**Issue by gjunqueira** [petl-developers/petl#467]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
# Your code here
>>> ep.receita('/input/receita_2018.xlsx')
/usr/local/lib/python3.6/site-packages/petl/io/db.py:362: UserWarning: DB-API extension cursor.connection used
  truncate=truncate)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pg8000/core.py", line 1776, in execute
    ps = cache['ps'][key]
KeyError: ('INSERT INTO "encantadors.receita_por_natureza" ("data", "codigo_receita", "descricao_receita", "arrecadado") VALUES (%s, %s, %s, %s)', ((1082, 0, <function Connection.__init__.<locals>.date_out at 0x7f031ad36d08>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x7f0320ce9e18>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x7f0320ce9e18>), (21, 1, <built-in method pack of Struct object at 0x7f031b6dad18>)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/gaet/encantadors/process.py", line 28, in receita
    petl.appenddb(excel, cur, tbl)
  File "/usr/local/lib/python3.6/site-packages/petl/io/db.py", line 624, in appenddb
    truncate=False)
  File "/usr/local/lib/python3.6/site-packages/petl/io/db.py", line 362, in _todb
    truncate=truncate)
  File "/usr/local/lib/python3.6/site-packages/petl/io/db.py", line 528, in _todb_dbapi_cursor
    cursor.executemany(insertquery, it)
  File "/usr/local/lib/python3.6/site-packages/pg8000/core.py", line 886, in executemany
    self.execute(operation, parameters)
  File "/usr/local/lib/python3.6/site-packages/pg8000/core.py", line 861, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib/python3.6/site-packages/pg8000/core.py", line 1835, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python3.6/site-packages/pg8000/core.py", line 1974, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: {'S': 'ERROR', 'V': 'ERROR', 'C': '42P01', 'M': 'relation "encantadors.receita_por_natureza" does not exist', 'P': '13', 'F': 'parse_relation.c', 'L': '1180', 'R': 'parserOpenTable'}
```

#### Problem description

When trying to insert on a table with its qualified name (<schema_name>.<table_name>), petl does not find the table.

#### Version and installation information

Python 3.6.3 (default, Oct  4 2017, 00:32:36)
[GCC 5.3.0] on linux
>>> petl.__version__
'1.2.0'

#### Additional info

I guess this is related to quoting. Postgres accept "atable" and atable as equivalents (say `describe "atable"` or `describe atable`), but this is not true for "aschema.atable" and aschema.atable (it should be "aschema"."atable" to work).

**Comment by alimanfoo** [comment]
Thanks for reporting. I don't know if there is a straightforward fix for
this but any work in that direction is welcome.
