### ISSUE TITLE
Cannot pass 'encoding_override' to 'fromxls' for proper decoding

### ISSUE THREAD

**Issue by gjunqueira** [petl-developers/petl#469]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
>>> import petl
>>> a = petl.fromxls('/input/ba_una/receitas_20161201_20161231.xls', 0)
>>> a.head()
*** WARNING: on_demand is not supported for this Excel version.
*** Setting on_demand to False.
*** No CODEPAGE record, no encoding_override: will use 'ascii'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/petl/util/vis.py", line 135, in _table_repr
    return str(look(table))
  File "/usr/local/lib/python3.7/site-packages/petl/util/vis.py", line 104, in __repr__
    table, overflow = _vis_overflow(self.table, self.limit)
  File "/usr/local/lib/python3.7/site-packages/petl/util/vis.py", line 528, in _vis_overflow
    table = list(islice(table, 0, limit+2))
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 630, in iterrowslice
    yield tuple(next(it))  # fields
  File "/usr/local/lib/python3.7/site-packages/petl/io/xls.py", line 36, in __iter__
    wb = xlutils_view.View(self.filename)
  File "/usr/local/lib/python3.7/site-packages/petl/io/xlutils_view.py", line 117, in __init__
    self.book = open_workbook(path, formatting_info=0, on_demand=True)
  File "/usr/local/lib/python3.7/site-packages/xlrd/__init__.py", line 157, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python3.7/site-packages/xlrd/book.py", line 108, in open_workbook_xls
    bk.fake_globals_get_sheet()
  File "/usr/local/lib/python3.7/site-packages/xlrd/book.py", line 732, in fake_globals_get_sheet
    self.get_sheets()
  File "/usr/local/lib/python3.7/site-packages/xlrd/book.py", line 723, in get_sheets
    self.get_sheet(sheetno)
  File "/usr/local/lib/python3.7/site-packages/xlrd/book.py", line 714, in get_sheet
    sh.read(self)
  File "/usr/local/lib/python3.7/site-packages/xlrd/sheet.py", line 820, in read
    strg = unpack_string(data, 6, bk.encoding or bk.derive_encoding(), lenlen=2)
  File "/usr/local/lib/python3.7/site-packages/xlrd/biffh.py", line 250, in unpack_string
    return unicode(data[pos:pos+nchars], encoding)
  File "/usr/local/lib/python3.7/site-packages/xlrd/timemachine.py", line 31, in <lambda>
    unicode = lambda b, enc: b.decode(enc)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 5: ordinal not in range(128)
```

#### Problem description

I am dealing with an old excel XLS file and I cannot read it with `fromxls` because `xlrd` is assuming `ascii` but the encoding is actually “cp1252".

Could you please allow `fromxls` to receive an extra parameter `encoding_override` so we can instruct `petl` to pass it along to `xlrd.open_workbook` so the file can be properly decoded?

Thanks in advance,

#### Version and installation information

Python 3.7.3 (default, May 11 2019, 02:00:41)
[GCC 8.3.0] on linux

* Operating system: Mac
* How petl was installed: pip

**Comment by alimanfoo** [comment]
Hi @gjunqueira, thanks for the report. It would seem reasonable to add additional ``**kwargs`` to ``petl.fromxls``, which are passed through to ``xlrd.open_workbook``. A PR in this direction would be welcome.
