### ISSUE TITLE
The petl package sometimes cause pymysql lost myql connection

### ISSUE THREAD

**Issue by minicloudsky** [petl-developers/petl#518]
bug info

python3/python36/lib/python3.6/site-packages/petl/io/db.py", line 156, in _iter_dbapi_connection
    for row in _iter_dbapi_cursor(cursor, query, *args, **kwargs):
python3/python36/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)

python3/python36/lib/python3.6/site-packages/pymysql/connections.py", line 699, in _read_bytes
   "Lost connection to MySQL server during query (%s)" % (e,))

**Comment by minicloudsky** [comment]
full stack trace as belows.
```
   Traceback (most recent call last):
     File "/home/python3/python36/lib/python3.6/site-packages/pymysql/connections.py", line 691, in _read_bytes
       data = self._rfile.read(num_bytes)
     File "/home/python3/pyenv-master/versions/3.6.5/lib/python3.6/socket.py", line 586, in readinto
       return self._sock.recv_into(b)
   TimeoutError: [Errno 110] Connection timed out
   
   During handling of the above exception, another exception occurred:
   
   Traceback (most recent call last):
     File "/home/project/meta_sys/Load_mysql_data.py", line 895, in <module>
       loading.loadTable()
     File "/home/project/meta_sys/Load_mysql_data.py", line 105, in loadTable
       insert_draft_result.len()
     File "/home/python3/python36/lib/python3.6/site-packages/petl/util/base.py", line 52, in len
       return len(self)
     File "/home/python3/python36/lib/python3.6/site-packages/petl/util/base.py", line 28, in __len__
       return sum(1 for _ in self)
     File "/home/python3/python36/lib/python3.6/site-packages/petl/util/base.py", line 28, in <genexpr>
       return sum(1 for _ in self)
     File "/home/python3/python36/lib/python3.6/site-packages/petl/transform/selects.py", line 130, in iterrowselect
       hdr = next(it)
     File "/home/python3/python36/lib/python3.6/site-packages/petl/transform/joins.py", line 334, in iterjoin
       lhdr = next(lit)
     File "/home/python3/python36/lib/python3.6/site-packages/petl/transform/sorts.py", line 271, in _iternocache
       hdr = next(it)
     File "/home/python3/python36/lib/python3.6/site-packages/petl/transform/joins.py", line 335, in iterjoin
       rhdr = next(rit)
     File "/home/python3/python36/lib/python3.6/site-packages/petl/transform/sorts.py", line 271, in _iternocache
       hdr = next(it)
     File "/home/python3/python36/lib/python3.6/site-packages/petl/io/db.py", line 156, in _iter_dbapi_connection
       for row in _iter_dbapi_cursor(cursor, query, *args, **kwargs):
     File "/home/python3/python36/lib/python3.6/site-packages/petl/io/db.py", line 163, in _iter_dbapi_cursor
       cursor.execute(query, *args, **kwargs)
     File "/home/python3/python36/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
       result = self._query(query)
     File "/home/python3/python36/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
       conn.query(q)
     File "/home/python3/python36/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
       self._affected_rows = self._read_query_result(unbuffered=unbuffered)
     File "/home/python3/python36/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
       result.read()
     File "/home/python3/python36/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
       first_packet = self.connection._read_packet()
     File "/home/python3/python36/lib/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
       packet_header = self._read_bytes(4)
     File "/home/python3/python36/lib/python3.6/site-packages/pymysql/connections.py", line 699, in _read_bytes
       "Lost connection to MySQL server during query (%s)" % (e,))
   pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 110] Connection timed out)')
```
my code like
import petl as etl
connection = get_mysql_connection()
sql = "select id,name user_token from user"
table = etl.fromdb(connection,sql)
print(table)

**Comment by juarezr** [comment]
Hi @minicloudsky,

Please tell us more details about the environment where the bug happens for trying to narrow a test case for finding it:
- How many records your query returns ?
- What are the field types of the query ? 
- The MySQL database is running in local machine or remote ?
- It only this query that have the problem ?
- If you query without petl, just with `pymysql` and `SQLAlchemy`, it works ?
- It's possible to write a test case for it ?
