### ISSUE TITLE
Python 3.9 support "No module named '_bz2'" ?

### ISSUE THREAD

**Issue by jossefaz** [petl-developers/petl#562]
#### Minimal, reproducible code sample, a copy-pastable example if possible
With python 3.9, brand new project, brand new pip environment, `petl` is the only package installed (just wanted to test it)
```
pip install petl
```

```python
import petl
```

#### Problem description

Importing Petl throw `ModuleNotFoundError`.

#### Version and installation information

* Value of ``petl.__version__`` : 1.7.4 (got with `pip freeze` since petl.__version__ cannot be performed)
* Version of Python interpreter : 3.9
* Operating system : Linux
* How petl was installed : `pip install petl`

#### Traceback : 

```python
Python 3.9.6 (default, Jul 18 2021, 16:57:48) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import petl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jossefaz/projects/petl/venv/lib/python3.9/site-packages/petl/__init__.py", line 7, in <module>
    from petl import util
  File "/home/jossefaz/projects/petl/venv/lib/python3.9/site-packages/petl/util/__init__.py", line 13, in <module>
    from petl.util.vis import look, lookall, lookstr, lookallstr, see
  File "/home/jossefaz/projects/petl/venv/lib/python3.9/site-packages/petl/util/vis.py", line 12, in <module>
    from petl.io.sources import MemorySource
  File "/home/jossefaz/projects/petl/venv/lib/python3.9/site-packages/petl/io/__init__.py", line 5, in <module>
    from petl.io.sources import FileSource, GzipSource, BZ2Source, ZipSource, \
  File "/home/jossefaz/projects/petl/venv/lib/python3.9/site-packages/petl/io/sources.py", line 9, in <module>
    import bz2
  File "/home/jossefaz/.pyenv/versions/3.9.6/lib/python3.9/bz2.py", line 18, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

```

**Comment by juarezr** [comment]
It's working in the [Github Actions/CI](https://github.com/petl-developers/petl/runs/2798956098?check_suite_focus=true#step:12:132) and also locally on my computer:

``` bash
$ python
Python 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import petl
>>> print(petl.__version__)
1.7.4
>>> import bz2
>>> exit()
$ pip list
Package    Version
---------- -------
petl       1.7.4
pip        21.2.4
setuptools 57.4.0
wheel      0.37.0
```

Please confirm if this works with a clean `pip` environment (`python3.9` without `pip install petl`) in your computer:

``` python
import os
import io
import gzip
import sys
import bz2
import zipfile
from contextlib import contextmanager
import subprocess
import logging
```

Also, what Linux distro/version are you using?

**Comment by juarezr** [comment]
Looks like a duplicate of #415
